# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ngraph/op_graph/hetr_grpc/hetr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ngraph.op_graph.serde import ops_pb2 as ngraph_dot_op__graph_dot_serde_dot_ops__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ngraph/op_graph/hetr_grpc/hetr.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n$ngraph/op_graph/hetr_grpc/hetr.proto\x1a\x1fngraph/op_graph/serde/ops.proto\"F\n\x05Value\x12\x19\n\x06scalar\x18\x01 \x01(\x0b\x32\x07.ScalarH\x00\x12\x19\n\x06tensor\x18\x02 \x01(\x0b\x32\x07.TensorH\x00\x42\x07\n\x05value\"(\n\x0c\x42uildRequest\x12\x18\n\x10transformer_type\x18\x01 \x01(\t\"\x1c\n\nBuildReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\"b\n\x12\x43omputationRequest\x12\x1b\n\x08subgraph\x18\x01 \x01(\x0b\x32\t.GraphDef\x12\x14\n\x07returns\x18\x02 \x03(\x0b\x32\x03.Op\x12\x19\n\x0cplaceholders\x18\x03 \x03(\x0b\x32\x03.Op\"#\n\x10\x43omputationReply\x12\x0f\n\x07\x63omp_id\x18\x01 \x01(\x05\";\n\x10\x46\x65\x65\x64InputRequest\x12\x0f\n\x07\x63omp_id\x18\x01 \x01(\x05\x12\x16\n\x06values\x18\x02 \x03(\x0b\x32\x06.Value\" \n\x0e\x46\x65\x65\x64InputReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\"$\n\x11GetResultsRequest\x12\x0f\n\x07\x63omp_id\x18\x01 \x01(\x05\":\n\x0fGetResultsReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x17\n\x07results\x18\x02 \x03(\x0b\x32\x06.Value2\xda\x01\n\x04Hetr\x12\x30\n\x10\x42uildTransformer\x12\r.BuildRequest\x1a\x0b.BuildReply\"\x00\x12\x37\n\x0b\x43omputation\x12\x13.ComputationRequest\x1a\x11.ComputationReply\"\x00\x12\x31\n\tFeedInput\x12\x11.FeedInputRequest\x1a\x0f.FeedInputReply\"\x00\x12\x34\n\nGetResults\x12\x12.GetResultsRequest\x1a\x10.GetResultsReply\"\x00\x62\x06proto3')
  ,
  dependencies=[ngraph_dot_op__graph_dot_serde_dot_ops__pb2.DESCRIPTOR,])




_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scalar', full_name='Value.scalar', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tensor', full_name='Value.tensor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='Value.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=73,
  serialized_end=143,
)


_BUILDREQUEST = _descriptor.Descriptor(
  name='BuildRequest',
  full_name='BuildRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transformer_type', full_name='BuildRequest.transformer_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=185,
)


_BUILDREPLY = _descriptor.Descriptor(
  name='BuildReply',
  full_name='BuildReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='BuildReply.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=215,
)


_COMPUTATIONREQUEST = _descriptor.Descriptor(
  name='ComputationRequest',
  full_name='ComputationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subgraph', full_name='ComputationRequest.subgraph', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='returns', full_name='ComputationRequest.returns', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='placeholders', full_name='ComputationRequest.placeholders', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=315,
)


_COMPUTATIONREPLY = _descriptor.Descriptor(
  name='ComputationReply',
  full_name='ComputationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='comp_id', full_name='ComputationReply.comp_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=352,
)


_FEEDINPUTREQUEST = _descriptor.Descriptor(
  name='FeedInputRequest',
  full_name='FeedInputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='comp_id', full_name='FeedInputRequest.comp_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='FeedInputRequest.values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=413,
)


_FEEDINPUTREPLY = _descriptor.Descriptor(
  name='FeedInputReply',
  full_name='FeedInputReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='FeedInputReply.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=447,
)


_GETRESULTSREQUEST = _descriptor.Descriptor(
  name='GetResultsRequest',
  full_name='GetResultsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='comp_id', full_name='GetResultsRequest.comp_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=485,
)


_GETRESULTSREPLY = _descriptor.Descriptor(
  name='GetResultsReply',
  full_name='GetResultsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='GetResultsReply.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='results', full_name='GetResultsReply.results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=545,
)

_VALUE.fields_by_name['scalar'].message_type = ngraph_dot_op__graph_dot_serde_dot_ops__pb2._SCALAR
_VALUE.fields_by_name['tensor'].message_type = ngraph_dot_op__graph_dot_serde_dot_ops__pb2._TENSOR
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['scalar'])
_VALUE.fields_by_name['scalar'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['tensor'])
_VALUE.fields_by_name['tensor'].containing_oneof = _VALUE.oneofs_by_name['value']
_COMPUTATIONREQUEST.fields_by_name['subgraph'].message_type = ngraph_dot_op__graph_dot_serde_dot_ops__pb2._GRAPHDEF
_COMPUTATIONREQUEST.fields_by_name['returns'].message_type = ngraph_dot_op__graph_dot_serde_dot_ops__pb2._OP
_COMPUTATIONREQUEST.fields_by_name['placeholders'].message_type = ngraph_dot_op__graph_dot_serde_dot_ops__pb2._OP
_FEEDINPUTREQUEST.fields_by_name['values'].message_type = _VALUE
_GETRESULTSREPLY.fields_by_name['results'].message_type = _VALUE
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['BuildRequest'] = _BUILDREQUEST
DESCRIPTOR.message_types_by_name['BuildReply'] = _BUILDREPLY
DESCRIPTOR.message_types_by_name['ComputationRequest'] = _COMPUTATIONREQUEST
DESCRIPTOR.message_types_by_name['ComputationReply'] = _COMPUTATIONREPLY
DESCRIPTOR.message_types_by_name['FeedInputRequest'] = _FEEDINPUTREQUEST
DESCRIPTOR.message_types_by_name['FeedInputReply'] = _FEEDINPUTREPLY
DESCRIPTOR.message_types_by_name['GetResultsRequest'] = _GETRESULTSREQUEST
DESCRIPTOR.message_types_by_name['GetResultsReply'] = _GETRESULTSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'ngraph.op_graph.hetr_grpc.hetr_pb2'
  # @@protoc_insertion_point(class_scope:Value)
  ))
_sym_db.RegisterMessage(Value)

BuildRequest = _reflection.GeneratedProtocolMessageType('BuildRequest', (_message.Message,), dict(
  DESCRIPTOR = _BUILDREQUEST,
  __module__ = 'ngraph.op_graph.hetr_grpc.hetr_pb2'
  # @@protoc_insertion_point(class_scope:BuildRequest)
  ))
_sym_db.RegisterMessage(BuildRequest)

BuildReply = _reflection.GeneratedProtocolMessageType('BuildReply', (_message.Message,), dict(
  DESCRIPTOR = _BUILDREPLY,
  __module__ = 'ngraph.op_graph.hetr_grpc.hetr_pb2'
  # @@protoc_insertion_point(class_scope:BuildReply)
  ))
_sym_db.RegisterMessage(BuildReply)

ComputationRequest = _reflection.GeneratedProtocolMessageType('ComputationRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTATIONREQUEST,
  __module__ = 'ngraph.op_graph.hetr_grpc.hetr_pb2'
  # @@protoc_insertion_point(class_scope:ComputationRequest)
  ))
_sym_db.RegisterMessage(ComputationRequest)

ComputationReply = _reflection.GeneratedProtocolMessageType('ComputationReply', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTATIONREPLY,
  __module__ = 'ngraph.op_graph.hetr_grpc.hetr_pb2'
  # @@protoc_insertion_point(class_scope:ComputationReply)
  ))
_sym_db.RegisterMessage(ComputationReply)

FeedInputRequest = _reflection.GeneratedProtocolMessageType('FeedInputRequest', (_message.Message,), dict(
  DESCRIPTOR = _FEEDINPUTREQUEST,
  __module__ = 'ngraph.op_graph.hetr_grpc.hetr_pb2'
  # @@protoc_insertion_point(class_scope:FeedInputRequest)
  ))
_sym_db.RegisterMessage(FeedInputRequest)

FeedInputReply = _reflection.GeneratedProtocolMessageType('FeedInputReply', (_message.Message,), dict(
  DESCRIPTOR = _FEEDINPUTREPLY,
  __module__ = 'ngraph.op_graph.hetr_grpc.hetr_pb2'
  # @@protoc_insertion_point(class_scope:FeedInputReply)
  ))
_sym_db.RegisterMessage(FeedInputReply)

GetResultsRequest = _reflection.GeneratedProtocolMessageType('GetResultsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETRESULTSREQUEST,
  __module__ = 'ngraph.op_graph.hetr_grpc.hetr_pb2'
  # @@protoc_insertion_point(class_scope:GetResultsRequest)
  ))
_sym_db.RegisterMessage(GetResultsRequest)

GetResultsReply = _reflection.GeneratedProtocolMessageType('GetResultsReply', (_message.Message,), dict(
  DESCRIPTOR = _GETRESULTSREPLY,
  __module__ = 'ngraph.op_graph.hetr_grpc.hetr_pb2'
  # @@protoc_insertion_point(class_scope:GetResultsReply)
  ))
_sym_db.RegisterMessage(GetResultsReply)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class HetrStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.BuildTransformer = channel.unary_unary(
          '/Hetr/BuildTransformer',
          request_serializer=BuildRequest.SerializeToString,
          response_deserializer=BuildReply.FromString,
          )
      self.Computation = channel.unary_unary(
          '/Hetr/Computation',
          request_serializer=ComputationRequest.SerializeToString,
          response_deserializer=ComputationReply.FromString,
          )
      self.FeedInput = channel.unary_unary(
          '/Hetr/FeedInput',
          request_serializer=FeedInputRequest.SerializeToString,
          response_deserializer=FeedInputReply.FromString,
          )
      self.GetResults = channel.unary_unary(
          '/Hetr/GetResults',
          request_serializer=GetResultsRequest.SerializeToString,
          response_deserializer=GetResultsReply.FromString,
          )


  class HetrServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def BuildTransformer(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Computation(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def FeedInput(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetResults(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_HetrServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'BuildTransformer': grpc.unary_unary_rpc_method_handler(
            servicer.BuildTransformer,
            request_deserializer=BuildRequest.FromString,
            response_serializer=BuildReply.SerializeToString,
        ),
        'Computation': grpc.unary_unary_rpc_method_handler(
            servicer.Computation,
            request_deserializer=ComputationRequest.FromString,
            response_serializer=ComputationReply.SerializeToString,
        ),
        'FeedInput': grpc.unary_unary_rpc_method_handler(
            servicer.FeedInput,
            request_deserializer=FeedInputRequest.FromString,
            response_serializer=FeedInputReply.SerializeToString,
        ),
        'GetResults': grpc.unary_unary_rpc_method_handler(
            servicer.GetResults,
            request_deserializer=GetResultsRequest.FromString,
            response_serializer=GetResultsReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Hetr', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaHetrServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def BuildTransformer(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Computation(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def FeedInput(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetResults(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaHetrStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def BuildTransformer(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    BuildTransformer.future = None
    def Computation(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Computation.future = None
    def FeedInput(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    FeedInput.future = None
    def GetResults(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetResults.future = None


  def beta_create_Hetr_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Hetr', 'BuildTransformer'): BuildRequest.FromString,
      ('Hetr', 'Computation'): ComputationRequest.FromString,
      ('Hetr', 'FeedInput'): FeedInputRequest.FromString,
      ('Hetr', 'GetResults'): GetResultsRequest.FromString,
    }
    response_serializers = {
      ('Hetr', 'BuildTransformer'): BuildReply.SerializeToString,
      ('Hetr', 'Computation'): ComputationReply.SerializeToString,
      ('Hetr', 'FeedInput'): FeedInputReply.SerializeToString,
      ('Hetr', 'GetResults'): GetResultsReply.SerializeToString,
    }
    method_implementations = {
      ('Hetr', 'BuildTransformer'): face_utilities.unary_unary_inline(servicer.BuildTransformer),
      ('Hetr', 'Computation'): face_utilities.unary_unary_inline(servicer.Computation),
      ('Hetr', 'FeedInput'): face_utilities.unary_unary_inline(servicer.FeedInput),
      ('Hetr', 'GetResults'): face_utilities.unary_unary_inline(servicer.GetResults),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Hetr_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Hetr', 'BuildTransformer'): BuildRequest.SerializeToString,
      ('Hetr', 'Computation'): ComputationRequest.SerializeToString,
      ('Hetr', 'FeedInput'): FeedInputRequest.SerializeToString,
      ('Hetr', 'GetResults'): GetResultsRequest.SerializeToString,
    }
    response_deserializers = {
      ('Hetr', 'BuildTransformer'): BuildReply.FromString,
      ('Hetr', 'Computation'): ComputationReply.FromString,
      ('Hetr', 'FeedInput'): FeedInputReply.FromString,
      ('Hetr', 'GetResults'): GetResultsReply.FromString,
    }
    cardinalities = {
      'BuildTransformer': cardinality.Cardinality.UNARY_UNARY,
      'Computation': cardinality.Cardinality.UNARY_UNARY,
      'FeedInput': cardinality.Cardinality.UNARY_UNARY,
      'GetResults': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Hetr', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
