# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ngraph.transformers.hetr.hetr_pb2 as ngraph_dot_transformers_dot_hetr_dot_hetr__pb2


class HetrStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BuildTransformer = channel.unary_unary(
        '/Hetr/BuildTransformer',
        request_serializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.BuildTransformerRequest.SerializeToString,
        response_deserializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.BuildTransformerReply.FromString,
        )
    self.CloseTransformer = channel.unary_unary(
        '/Hetr/CloseTransformer',
        request_serializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.CloseTransformerRequest.SerializeToString,
        response_deserializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.CloseTransformerReply.FromString,
        )
    self.Computation = channel.stream_unary(
        '/Hetr/Computation',
        request_serializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.ComputationRequest.SerializeToString,
        response_deserializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.ComputationReply.FromString,
        )
    self.FeedInput = channel.unary_unary(
        '/Hetr/FeedInput',
        request_serializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.FeedInputRequest.SerializeToString,
        response_deserializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.FeedInputReply.FromString,
        )
    self.GetResults = channel.unary_unary(
        '/Hetr/GetResults',
        request_serializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.GetResultsRequest.SerializeToString,
        response_deserializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.GetResultsReply.FromString,
        )
    self.Close = channel.unary_unary(
        '/Hetr/Close',
        request_serializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.CloseRequest.SerializeToString,
        response_deserializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.CloseReply.FromString,
        )


class HetrServicer(object):

  def BuildTransformer(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CloseTransformer(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Computation(self, request_iterator, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FeedInput(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetResults(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Close(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HetrServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BuildTransformer': grpc.unary_unary_rpc_method_handler(
          servicer.BuildTransformer,
          request_deserializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.BuildTransformerRequest.FromString,
          response_serializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.BuildTransformerReply.SerializeToString,
      ),
      'CloseTransformer': grpc.unary_unary_rpc_method_handler(
          servicer.CloseTransformer,
          request_deserializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.CloseTransformerRequest.FromString,
          response_serializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.CloseTransformerReply.SerializeToString,
      ),
      'Computation': grpc.stream_unary_rpc_method_handler(
          servicer.Computation,
          request_deserializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.ComputationRequest.FromString,
          response_serializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.ComputationReply.SerializeToString,
      ),
      'FeedInput': grpc.unary_unary_rpc_method_handler(
          servicer.FeedInput,
          request_deserializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.FeedInputRequest.FromString,
          response_serializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.FeedInputReply.SerializeToString,
      ),
      'GetResults': grpc.unary_unary_rpc_method_handler(
          servicer.GetResults,
          request_deserializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.GetResultsRequest.FromString,
          response_serializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.GetResultsReply.SerializeToString,
      ),
      'Close': grpc.unary_unary_rpc_method_handler(
          servicer.Close,
          request_deserializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.CloseRequest.FromString,
          response_serializer=ngraph_dot_transformers_dot_hetr_dot_hetr__pb2.CloseReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Hetr', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
