FROM nvidia/cuda:7.0-devel-ubuntu14.04
# FROM ubuntu

RUN apt-get update && \
    apt-get install -y python-pip git && \
    apt-get clean autoclean && \
    apt-get autoremove -y
RUN pip install --upgrade pip

# build ngraph requirements
ADD requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

WORKDIR /root/private-ngraph
