FROM ngraph_base_cpu

# install neon
WORKDIR /root
RUN apt-get install -y python-dev && \
    apt-get clean autoclean && \
    apt-get autoremove -y

# install aeon dependency
RUN apt-get install -y libcurl4-openssl-dev clang libopencv-dev libsox-dev && \
    apt-get clean autoclean && \
    apt-get autoremove -y
RUN pip install git+https://github.com/NervanaSystems/aeon.git

WORKDIR /root/ngraph-test
ADD test_requirements.txt /root/ngraph-test/test_requirements.txt
RUN pip install -r test_requirements.txt

# necessary for tests/test_walkthrough.py which requires that ngraph is
# importable from an entrypoint not local to ngraph.
ADD . /root/ngraph-test
RUN pip install -e .
