FROM ngraph_base

# install dependencies
# python-dev and python-pip are installed in ngraph_base image 
# for the appropriate python2 or python3 version
WORKDIR /root
RUN apt-get update && \
    apt-get install -y cmake && \
    apt-get clean autoclean && \
    apt-get autoremove -y

# install aeon dependencies
RUN apt-get update && \
    apt-get install -y clang libcurl4-openssl-dev libopencv-dev libsox-dev libgtest-dev && \
    apt-get clean autoclean && \
    apt-get autoremove -y

WORKDIR /usr/src/gtest
RUN cmake CMakeLists.txt
RUN make
RUN cp *.a /usr/local/lib

WORKDIR /root/ngraph-test
ADD contrib/docker/private-aeon /root/private-aeon
WORKDIR /root/private-aeon
# workaround for missing requirement for aeon install
RUN echo "future" >> requirements.txt
RUN pip install -r requirements.txt
RUN mkdir -p build && cd build && cmake .. && pip install . && cd ..

WORKDIR /root/ngraph-test
ADD . /root/ngraph-test

# This disables a warning from opencv from a defunct driver
RUN ln /dev/null /dev/raw1394

# build Baidu's Warp-CTC 
# dependencies for deepspeech example
WORKDIR /root
RUN git clone https://github.com/baidu-research/warp-ctc.git 
RUN cd warp-ctc
ADD . /root/warp-ctc
WORKDIR /root/warp-ctc 
RUN mkdir -p build 
RUN cd build && cmake ../ && make && cd ../..
ENV WARP_CTC_PATH=/root/warp-ctc/build
ENV WARP_CTC_LIB=$WARP_CTC_PATH/libwarpctc.so
ENV LD_LIBRARY_PATH=$WARP_CTC_PATH:$LD_LIBRARY_PATH
RUN env
RUN ls -l $WARP_CTC_PATH

WORKDIR /root/ngraph-test
ADD . /root/ngraph-test
RUN make gpu_prepare
RUN make test_prepare
RUN make install

# add in autoflex.  This should will only be added if the user building
# this dockerfile has permission to access the autoflex repo.  This is a
# temporary solution to get things working quickly.
WORKDIR /root/ngraph-test
ADD contrib/docker/autoflex /root/autoflex
RUN pip install -e /root/autoflex

ADD tests/config/jupyter_nbconvert_config.py /root/.jupyter/jupyter_nbconvert_config.py

WORKDIR /root/ngraph-test
