FROM ngraph_base

# install neon
WORKDIR /root
RUN apt-get install -y python-dev && \
    apt-get clean autoclean && \
    apt-get autoremove -y

WORKDIR /root/ngraph-test
ADD test_requirements.txt /root/ngraph-test/test_requirements.txt
RUN pip install -r test_requirements.txt
ADD gpu_requirements.txt /root/ngraph-test/gpu_requirements.txt
RUN pip install -r gpu_requirements.txt

# add in autoflex.  This should will only be added if the user building
# this dockerfile has permission to access the autoflex repo.  This is a
# temporary solution to get things working quickly.
ADD contrib/docker/autoflex /root/autoflex
RUN pip install -e /root/autoflex

ADD tests/jupyter_nbconvert_config.py /root/.jupyter/jupyter_nbconvert_config.py

# make ngraph Makefile happy :-(
ENV VIRTUAL_ENV='making ngraph makefile happy'
