#!/bin/bash

# https://github.com/NVIDIA/nvidia-docker/releases
wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0/nvidia-docker_1.0.0-1_amd64.deb
sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb
cd /usr/local/cuda-8.0/samples/1_Utilities/deviceQuery
sudo make
